version: '2'
services:
  osmnames:
    build: .
    volumes:
      - .:/osmnames
      - ./data:${DATA_DIR}
    depends_on:
      - postgres
#    tmpfs: /tmp
    env_file: .env

  postgres:
    image: mdillon/postgis:11
    shm_size: 256mb
    environment:
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "54320:5432"
    volumes:
      - ./data/postgres_config.sh:/docker-entrypoint-initdb.d/postgres_config.sh
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
    driver: local